### ISSUE TITLE
Failing tests on Windows

### ISSUE THREAD

**Issue by thenewguy** [vikingco/django-locking#20]
Not sure what is going on here:
```
(django-locking) D:\path\to\django-locking>ver

Microsoft Windows [Version 6.3.9600]

(django-locking) D:\path\to\django-locking>python setup.py test > fail-test-log.log 2>&1


running test
Searching for freezegun
Best match: freezegun 0.3.5
Processing freezegun-0.3.5-py2.7.egg

Using d:\path\to\django-locking\.eggs\freezegun-0.3.5-py2.7.egg
Searching for python-dateutil!=2.0,>=1.0
Best match: python-dateutil 2.4.2
Processing python_dateutil-2.4.2-py2.7.egg

Using d:\path\to\django-locking\.eggs\python_dateutil-2.4.2-py2.7.egg
Searching for six
Best match: six 1.9.0
Processing six-1.9.0-py2.7.egg

Using d:\path\to\django-locking\.eggs\six-1.9.0-py2.7.egg
running egg_info
writing django_locking.egg-info\PKG-INFO
writing top-level names to django_locking.egg-info\top_level.txt
writing dependency_links to django_locking.egg-info\dependency_links.txt
reading manifest file 'django_locking.egg-info\SOURCES.txt'
writing manifest file 'django_locking.egg-info\SOURCES.txt'
running build_ext
EEEEEEEEEE
======================================================================
ERROR: test_acquire_and_release (locking.tests.NonBlockingLockTest)
Tests an aquire/release cycle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 20, in test_acquire_and_release
    l = NonBlockingLock.objects.acquire_lock(self.user)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_acquire_and_renew (locking.tests.NonBlockingLockTest)
Tests an aquire/renew cycle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 39, in test_acquire_and_renew
    l = NonBlockingLock.objects.acquire_lock(self.user)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_context_manager (locking.tests.NonBlockingLockTest)
A lock can be used as a context manager
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 106, in test_context_manager
    with NonBlockingLock.objects.acquire_lock(self.user):
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_expired (locking.tests.NonBlockingLockTest)
Test the expired locks
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 96, in test_expired
    l = NonBlockingLock.objects.acquire_lock(self.user, max_age=0)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_lock_twice (locking.tests.NonBlockingLockTest)
Tests a double locking (lock and try to lock again)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 51, in test_lock_twice
    l = NonBlockingLock.objects.acquire_lock(self.user)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_model (locking.tests.NonBlockingLockTest)
Test the model
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 67, in test_model
    l = NonBlockingLock.objects.acquire_lock(self.user, max_age=10)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_obj_with_expired_lock_is_not_locked (locking.tests.NonBlockingLockTest)
Tests that manager.is_locked returns False if locks are expired
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 32, in test_obj_with_expired_lock_is_not_locked
    NonBlockingLock.objects.acquire_lock(self.user, max_age=1)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_reloCreating test database for alias 'default'...
Destroying test database for alias 'default'...
ck (locking.tests.NonBlockingLockTest)
Test to allow lock if lock is expired
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 86, in test_relock
    l = NonBlockingLock.objects.acquire_lock(self.user, max_age=10)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_unicode (locking.tests.NonBlockingLockTest)
Test the __unicode__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 78, in test_unicode
    l = NonBlockingLock.objects.acquire_lock(self.user)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

======================================================================
ERROR: test_unlock_twice (locking.tests.NonBlockingLockTest)
Tests a double unlocking (unlock and try to unlock again)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\path\to\django-locking\locking\tests.py", line 59, in test_unlock_twice
    l = NonBlockingLock.objects.acquire_lock(self.user)
  File "D:\path\to\django-locking\locking\models.py", line 58, in acquire_lock
    raise AlreadyLocked()
AlreadyLocked

----------------------------------------------------------------------
Ran 10 tests in 0.385s

FAILED (errors=10)
```

Raising the issue until I can look into it further

**Comment by thenewguy** [comment]
Ignore that. Wrong branch
